---
title: "Journal Articles"
---

### About the misappropiation of genetics
<br>
<a href="http://dx.doi.org/10.3998/ptb.6959004.0009.012" target="_blank" rel="noopener noreferrer" title="Are Clusters Races?">_Are Clusters Races? A Discussion of the Rhetorical Appropriation of Rosenberg et al.'s 'Genetic Structure of Human Populations'_</a>, Melissa Wills, 2017.
<a href="https://www.nature.com/articles/d41586-022-03252-z" target="_blank" rel="noopener noreferrer" title="Counter the weaponization of genetics research by extremists">_Counter the weaponization of genetics research by extremists_</a> Jedidiah Carlson et al., 2022.
<a href="https://doi.org/10.1126/science.abm7530" target="_blank" rel="noopener noreferrer" title="Getting genetic ancestry right for science and society">_Getting genetic ancestry right for science and society_</a>, Anna C.F. Lewis et al., 2022.
<a href="https://doi.org/10.3389/fgene.2023.1044555" target="_blank" rel="noopener noreferrer" title="Ancestry: How researchers use it and what they mean by it">_Ancestry: How researchers use it and what they mean by it'_</a>, Bege Dauda et al., 2023.
<br><br><br>

### About the troubling history and legacy of eugenics
<br>
<a href="https://doi.org/10.1177/0957154X18808666" target="_blank" rel="noopener noreferrer" title="Eugenic concerns, scientific practices?">_Eugenic concerns, scientific practices: international relations in the establishment of psychiatric genetics in Germany, Britain, the USA and Scandinavia, c.1910-60_</a>, Volker Roelcke et al., 2018.
<br><br><br>

### About polygenic embryo screening
<br>
<a href="https://doi.org/10.1111/aogs.13831" target="_blank" rel="noopener noreferrer" title="Preimplantation genetic testing legislation and accessibility in the Nordic countries">_Preimplantation genetic testing legislation and accessibility in the Nordic countries_</a>, Julius Hreinsson et al., 2020.
<a href="https://doi.org/10.1111/aogs.13882" target="_blank" rel="noopener noreferrer" title="Personalized medicine for the embryo and the fetus - Options in modern genetics influence preconception and prenatal choices">_Personalized medicine for the embryo and the fetus - Options in modern genetics influence preconception and prenatal choices_</a>, Hans Jakob Ingerslev et al., 2020.
<a href="https://doi.org/10.1016/s2215-0366(22)00157-2" target="_blank" rel="noopener noreferrer" title="Concerns about the use of polygenic embryo screening for psychiatric and cognitive traits">_Concerns about the use of polygenic embryo screening for psychiatric and cognitive traits_</a>, Todd Lencz et al., 2022.
<a href="https://doi.org/10.1111/aogs.14052" target="_blank" rel="noopener noreferrer" title="National data on the early clinical use of non-invasive prenatal testing in public and private healthcare in Denmark 2013-2017">_National data on the early clinical use of non-invasive prenatal testing in public and private healthcare in Denmark 2013-2017_</a>, Ida C.B. Lund et al., 2020.
<a href="https://doi.org/10.1002/pd.6088" target="_blank" rel="noopener noreferrer" title="Patients' choices and opinions on chorionic villous sampling and non-invasive alternatives for prenatal testing following preimplantation genetic testing for hereditary disorders: A cross-sectional questionnaire study">_Patients' choices and opinions on chorionic villous sampling and non-invasive alternatives for prenatal testing following preimplantation genetic testing for hereditary disorders: A cross-sectional questionnaire study_</a>, Christian L.F. Toft et al., 2022.
<br><br><br>