---
title: "Second meeting - Wednesday 17th May 2023"
---

## History of eugenics
<br>
The theme of the second ADWG meeting was the history and legacy of eugenics in (psychiatric) genetics, and was inspired by <a href="https://www.adamrutherford.com/" target="_blank" rel="noopener noreferrer" title="About Adam Rutherford">Adam Rutherford</a>'s 50 minutes Podcast about <a href="https://howtoacademy.com/podcasts/adam-rutherford-the-troubling-history-of-eugenics/" target="_blank" rel="noopener noreferrer" title="Adam Rutherford - The Troubling History of Eugenics">the troubling history of eugenics</a>. 
We talked about how eugenics was formed as an ancient ideology, and how it developed through the work of Charles Darwin, Gregor Mendel and Francis Galton, before it was put into policy and practice in the 20th century. We spent some time focusing on eugenics in Denmark by talking, among others, about the Girl's Home on Sprogø (read more <a href="https://sundogbaelt.dk/forbindelser/storebaelt/sprogo/pigehjemmet-pa-sprogo/" target="_blank" rel="noopener noreferrer" title="Pigehjemmet på Sprogø">here</a> and <a href="https://cphpost.dk/2021-04-18/history/spectre-of-sprogo-the-dark-chapter-denmark-would-rather-forget/" target="_blank" rel="noopener noreferrer" title="Spectre of Sprogø">here</a>) and the IUD campaign in Greenland (read more <a href="https://sum.dk/nyheder/2022/september/danmark-og-groenland-indgaar-aftale-om-udredning-af-%E2%80%9Dspiralsagen%E2%80%9D" target="_blank" rel="noopener noreferrer" title="Spiralsagen">here</a> and <a href="https://www.dr.dk/lyd/p1/spiralkampagnen" target="_blank" rel="noopener noreferrer" title="Spiralkampagnen">here</a>).
Furthermore, we discussed that eugenics are unfortunately still present in Denmark at the present day:

* <a href="https://doi.org/10.1016/j.paid.2011.02.031" target="_blank" rel="noopener noreferrer" title="The decay of Western civilization: Double relaxed Darwinian Selection">_The decay of Western civilization: Double relaxed Darwinian Selection_</a>, published by Helmuth Nyborg in _Personality and Individual Differences_ in July 2012.
* <a href="http://doi.org/10.46469/mq.2022.62.3.4" target="_blank" rel="noopener noreferrer" title="Europeans Have Larger Testes than Sub-Saharan Africans but Lower Testosterone Levels">_Europeans Have Larger Testes than Sub-Saharan Africans but Lower Testosterone Levels_</a>, published by Edward Dutton et al. in _Mankind Quarterly_ in March 2022.
* <a href="https://front.emilkirkegaard.dk/" target="_blank" rel="noopener noreferrer" title="Emil Ole William Kirkegaard">Emil Ole William Kirkegaard's webpage</a>.

<br>
Finally, we discussed the legacy of eugenics in (psychiatric) genetics and whether we are already living in the _Brave New World_.
<br><br>

You can find the slides (in PDF format) used in connection to this meeting <a href="Slides/ADWG_meeting2_eugenics_history.pdf" target="_blank" rel="noopener noreferrer" title="ADWG meeting - History of eugenics">here</a>.
<br><br><br>

### Merriam-Webster dictionary: Eugenics
<a href="https://www.merriam-webster.com/dictionary/eugenics" target="_blank" rel="noopener noreferrer" title="Merriam-Webster Dictionary Definition of Eugenics">_the practice or advocacy of controlled selective breeding of human populations (as by sterilization) to improve the population's genetic composition_</a>
<br><br><br>

### Further information:
<br>

* <a href="https://www.adamrutherford.com/eugenics" target="_blank" rel="noopener noreferrer" title="Adam Rutherford - Control">Control - The dark history and troubling present of eugenics</a>, by Adam Rutherford.
* <a href="https://www.adamrutherford.com/race" target="_blank" rel="noopener noreferrer" title="Adam Rutherford - How to argue with a racist">How to argue with a racist</a>, by Adam Rutherford.
* <a href="https://www.bbc.co.uk/programmes/m001fd36" target="_blank" rel="noopener noreferrer" title="Bad Blood: The Story of Eugenics">Bad Blood: The Story of Eugenics</a> a BBC Radio 4 podcast by Adam Rutherford.




